services:
  app:
    build:
      context: .dev/app
    volumes:
      - ./:/var/www/html
    ports:
     - "127.0.0.1:8080:80"
    # Enable this to test container compilation
    #environment:
    #  - CONTAINER_CACHE=1

  cli:
    build:
      context: .dev/cli
    volumes:
      - ./:/var/www/html
    command: tail -f /dev/null
    stop_grace_period: 1s
    working_dir: /var/www/html
    environment:
      - XDEBUG_MODE=coverage
