name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [phpcs, phpstan, phpunit]
        include:
          - php: 8.3
            gist: dd8853a6f8af0b6b2e88ab392ba359b2
          - php: 8.4
            gist: dd8853a6f8af0b6b2e88ab392ba359b2

    env:
      XDEBUG_MODE: coverage
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"
          dev: yes
          php_extensions: fileinfo xdebug
      - name: Run Test ${{ matrix.test }}
        run: composer run ${{ matrix.test }}
        env:
          XDEBUG_MODE: coverage
      - name: Upload coverage to Codecov
        if: ${{ matrix.test == 'phpunit' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ matrix.gist }}
          filename: "ci-php${{ matrix.php }}.svg"
          label: "PHP ${{ matrix.php }}"
          message: "99.0%"
          color: orange
